import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { syncRelease } from "./scripts/sync-release.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
AI Notebook (ai-notebook) — Obsidian plugin
*/
`;

const prod = process.argv[2] === "production";

/** Always keep release/ai-notebook in sync (Obsidian install source of truth for this user). */
const syncPlugin = {
	name: "sync-release-ai-notebook",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;
			try {
				await syncRelease({ quiet: prod });
				if (prod) {
					console.log("synced → release/ai-notebook/");
				}
			} catch (e) {
				console.warn(
					"sync-release failed:",
					e instanceof Error ? e.message : e,
				);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [syncPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
